sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7
env:
  matrix:
    - PYZMQ='pyzmq>=15'
    - PYZMQ='pyzmq>=14,<15'
    - PYZMQ='pyzmq>=13,<14'
matrix:
  fast_finish: true
addons:
  apt:
    packages:
      - python-dev
      - libevent-dev
install:
  - "pip install nose $PYZMQ"
  - pip install .
script:
  - nosetests -v
